import {
  Injectable,
  Logger,
  ServiceUnavailableException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

import { EmailService } from '../email/email.service';
import { EmailRecipientsService } from '../email-recipients/email-recipients.service';
import { RecipientType } from '../email-recipients/dto/create-email-recipient.dto';
import { SendContactMessageDto } from './dto/send-contact-message.dto';

@Injectable()
export class ContactService {
  private readonly logger = new Logger(ContactService.name);

  constructor(
    private readonly emailService: EmailService,
    private readonly emailRecipientsService: EmailRecipientsService,
    private readonly configService: ConfigService,
  ) {}

  async sendContactMessage(dto: SendContactMessageDto) {
    const escape = (value: string) =>
      value
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');

    const generalRecipients =
      await this.emailRecipientsService.findActiveByType(RecipientType.GENERAL);
    const membershipRecipients =
      await this.emailRecipientsService.findActiveByType(
        RecipientType.MEMBERSHIP,
      );

    const recipientSet = new Set<string>([
      ...generalRecipients,
      ...membershipRecipients,
    ]);
    let recipientList = Array.from(recipientSet);

    const fallbackRecipient = this.configService.get<string>(
      'email.contactRecipient',
    );
    if (recipientList.length === 0 && fallbackRecipient) {
      recipientList = [fallbackRecipient];
    }

    if (recipientList.length === 0) {
      this.logger.error(
        'Contact message attempted but no general recipients are configured',
      );
      throw new ServiceUnavailableException(
        'Contact email is temporarily unavailable. Please try again later.',
      );
    }

    const submittedAt = new Date().toLocaleString('en-KE', {
      timeZone: 'Africa/Nairobi',
    });
    const escapedSubject = escape(dto.subject);
    const escapedName = escape(dto.name);
    const escapedEmail = escape(dto.email);
    const escapedPhone = dto.phone ? escape(dto.phone) : undefined;
    const escapedMessage = escape(dto.message);

    const adminHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #1f2933; }
          .container { max-width: 640px; margin: 0 auto; padding: 16px; }
          .header { background: #8B2332; color: #fff; padding: 18px; border-radius: 12px; }
          .content { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 20px; margin-top: 20px; }
          .field { margin-bottom: 12px; }
          .label { font-weight: 600; color: #8B2332; font-size: 14px; text-transform: uppercase; letter-spacing: 0.04em; }
          .value { margin-top: 4px; font-size: 15px; }
          .footer { margin-top: 18px; font-size: 13px; color: #64748b; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h2>New Website Message</h2>
            <p>${submittedAt}</p>
          </div>
          <div class="content">
            <div class="field">
              <div class="label">Subject</div>
              <div class="value">${escapedSubject}</div>
            </div>
            <div class="field">
              <div class="label">Full Name</div>
              <div class="value">${escapedName}</div>
            </div>
            <div class="field">
              <div class="label">Email</div>
              <div class="value">${escapedEmail}</div>
            </div>
            ${
              escapedPhone
                ? `
              <div class="field">
                <div class="label">Phone</div>
                <div class="value">${escapedPhone}</div>
              </div>
            `
                : ''
            }
            <div class="field">
              <div class="label">Message</div>
              <div class="value">${escapedMessage.replace(/\n/g, '<br/>')}</div>
            </div>
          </div>
          <div class="footer">
            This notification was generated by the APECK website contact form.
          </div>
        </div>
      </body>
      </html>
    `;

    const adminText = `
New Website Message (${submittedAt})

Subject: ${dto.subject}
Name: ${dto.name}
Email: ${dto.email}
${dto.phone ? `Phone: ${dto.phone}` : ''}

Message:
${dto.message}
    `;

    const acknowledgementHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #1f2933; }
          .container { max-width: 640px; margin: 0 auto; padding: 16px; }
          .header { background: #8B2332; color: #fff; padding: 18px; border-radius: 12px; text-align: center; }
          .content { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 20px; margin-top: 20px; }
          .footer { margin-top: 18px; font-size: 13px; color: #64748b; text-align: center; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h2>Message Received</h2>
          </div>
          <div class="content">
            <p>Dear ${escapedName},</p>
            <p>Thank you for reaching out to APECK. We have received your message with the subject "<strong>${escapedSubject}</strong>".</p>
            <p>Our team will review your message and get back to you as soon as possible.</p>
            <p>If your inquiry is urgent, please call us using the contacts listed on our website.</p>
            <p>Warm regards,<br/>The APECK Team</p>
          </div>
          <div class="footer">
            This is an automated confirmation email. Please do not reply directly to this message.
          </div>
        </div>
      </body>
      </html>
    `;

    const acknowledgementText = `
Dear ${dto.name},

Thank you for contacting APECK. We have received your message titled "${dto.subject}" and will get back to you soon.

Warm regards,
The APECK Team
    `;

    const adminSent = await this.emailService.sendEmail({
      to: recipientList,
      subject: `Website Contact: ${dto.subject}`,
      html: adminHtml,
      text: adminText,
    });

    const userSent = await this.emailService.sendEmail({
      to: dto.email,
      subject: 'We have received your message',
      html: acknowledgementHtml,
      text: acknowledgementText,
    });

    return { adminSent, userSent };
  }
}
